version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore(deps)"
    groups:
      rust-safe-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      rust-major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
